# This workflow will do a clean installation of node dependencies, cache/restore them, 
# build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Check out the repository's code using the checkout action
    - uses: actions/checkout@v4
    
    # Set up Node.js based on the version specified in the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # Install the dependencies using npm ci
    - run: npm ci
    
    # Build the source code if a build script is present in package.json
    - run: npm run build --if-present
    
    # Run the tests defined in package.json
    - run: npm test
    
    # Deploy the build using gh-pages
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
